package Appcharge.listeners;

import AppCharge.Utilities.TestUtil;
import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestResult;
import org.testng.Reporter;

import java.io.IOException;

public class CustomListeners implements ITestListener {

    public void onStart (ITestContext arg0)
    {

    }
    public void onFinish (ITestContext arg0)
    {

    }



    public void onTestFailedButWithinSuccessPercentage(ITestResult arg0)
{


}


    public void onTestFailure(ITestResult arg0) {

        System.setProperty("org.uncommons.reportng.escape-output", "false");
        try {
            TestUtil.captureScreenshot();
        } catch (IOException e){
         // to do autogenerated catch block
         e.printStackTrace();


        }

        Reporter.log("Clicking in search field successfully executed");
        Reporter.log("<a target = \'_blank\' href='C:\\source\\AppCharge\\error.jpg>Screenshot</a>");
        Reporter.log("<br>");
        //Reporter.log("<a target = \'_blank\' href='C:\\source\\AppCharge\\error.jpg>"><img src="+TestUtil.screenshotName+" height=200 width=200></img></a>");


    }

    public void onTestSkipped(ITestResult arg0) {

    }

    public void onTestStart(ITestResult arg0) {

    }
    public void onTestSuccess(ITestResult arg0) {

    }

}
